import AuthContextProvider from "@/context/AuthContext";
import "./globals.scss";
import MainLayoutContent from "./mainLayoutContent";
import { SpeedInsights } from "@vercel/speed-insights/next"
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthContextProvider>
      <MainLayoutContent>
        {children}
        <SpeedInsights />
      </MainLayoutContent>
    </AuthContextProvider>

  );
}
