"use client"
import Sidebar from "@/components/layouts/Sidebar";
import "./globals.scss";
import Navbar from "@/components/layouts/Navbar";
import { useState } from "react";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayoutContent({ children }) {
  const [sidebarIsOpen, setSidebarIsOpen] = useState(false)
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className="font-poppins">
        <div className="flex h-dvh min-h-svh bg-gray-950 text-white overflow-hidden relative lg:px-5">
          <Sidebar sidebarIsOpen={sidebarIsOpen} setSidebarIsOpen={setSidebarIsOpen} />
          <div className="grow flex overflow-hidden flex-col">
            <Navbar sidebarIsOpen={sidebarIsOpen} setSidebarIsOpen={setSidebarIsOpen} />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
