"use client"
import Sidebar from "@/components/layouts/Sidebar";
import "./globals.scss";
import Navbar from "@/components/layouts/Navbar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayoutContent({ children }) {
  return (
    <html lang="en">
      <body className="font-poppins">
        <div className="flex h-dvh min-h-svh bg-gray-950 text-white overflow-hidden relative p-5">
          <Sidebar />
          <div className="grow flex flex-col last:[&_*:has(.error)]:flex last:[&_*:has(.error)]:flex-col last:[&_*:has(.error)]:h-full">
            <Navbar/>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
