"use client"
import Sidebar from "@/components/layouts/Sidebar";
import "./globals.scss";
import Navbar from "@/components/layouts/Navbar";
import { useEffect, useState } from "react";
import AuthContextProvider from "@/context/AuthContext";
import { usePathname } from "next/navigation";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayoutContent({ children }) {
  const [sidebarIsOpen, setSidebarIsOpen] = useState(false)
  const pathName = usePathname()
  const [loginLayout, setLoginLayout] = useState(false)
  console.log({ pathName })

  useEffect(() => {
    setLoginLayout(pathName == '/sign-in' || pathName == '/sign-up')
  }, [pathName])

  return (
    <html lang="en">
      <body className="font-poppins">
        {/* <AuthContextProvider> */}
        <div className="flex h-dvh min-h-svh bg-gray-950 text-white overflow-hidden relative lg:px-5">

          {loginLayout ? <></> : <Sidebar sidebarIsOpen={sidebarIsOpen} setSidebarIsOpen={setSidebarIsOpen} />}

          <div className="grow flex overflow-hidden flex-col">
            {loginLayout ? <></> : <Navbar sidebarIsOpen={sidebarIsOpen} setSidebarIsOpen={setSidebarIsOpen} />}
            {children}
          </div>
        </div>
        {/* </AuthContextProvider> */}
      </body>
    </html>
  );
}
